twopirllc/pandas-ta

pandas_ta/performance/log_return.py
=> Update to log_return

pandas_ta/core.py, pandas_ta/utils.py
This PR is focused on create a few utility functions useful for mark ranges of ticks where a series is above/below another series or a constant value. For example, can be used easily to mark overbought or oversold periods from RSI indicator.
Please comment any improvement that could be done here o cases where it will fail.
=> Add above and below functions

pandas_ta/core.py
Hi,
Here there is a PR which is meant to be able to add prefixes and suffixes to the columns that are created using this package. The only thing required to be able to add this prefix or suffix is to add them as an argument.
Please comment any improvement that could be done here o cases where it will fail.
=> Append column prefixes suffixes

pandas_ta/core.py, pandas_ta/momentum/stoch.py, pandas_ta/trend/__init__.py, pandas_ta/trend/ha.py, pandas_ta/trend/supertrend.py, pandas_ta/volatility/atr.py
Issue #55 : addition of supertrend indicator
+ addition of Heikin-Ashi
+ addition of a line in kwargs doc for ATR.
=> Development : Add heikin-Ashi & supertrend TI

README.md, pandas_ta/core.py, pandas_ta/utils.py, setup.py
Multiprocessing is **not** enabled, so you will have to enable it before running ```strategy()```.
```python
df.ta.mp = True
dt.ta.strategy()
df.ta.strategy(timed=True, verbose=True)
df.ta.strategy(timed=True, verbose=True, cores=8)
```
=> ENH mp property + strategy multiprocessing support

pandas_ta/core.py, pandas_ta/trend/__init__.py, pandas_ta/trend/ttm_trend.py, tests/test_indicator_trend.py, tests/test_indicator_trend_ext.py
https://www.prorealcode.com/prorealtime-indicators/ttm-trend-price/
=> Add ttm trend

pandas_ta/core.py, setup.py
=> moving version to setup.py and using pkg_resources to fetch from core.py

pandas_ta/core.py
Hi @twopirllc,
Here I suggest a simple modification of the `_append()` method in `core.py`, to allow the user to rename via kwargs the column(s) names.
It works like this :
```
CustomStrategy = ta.Strategy(
name="MyStrat",
ta=[
{'kind':'bbands', 'params':(20,4), 'col_names':('name1', 'name2', 'name3')},
]
)
```
or alternatively :
`bb = df.ta.bbands(params=(20,4), append=True, col_names=('name1', 'name2', 'name3'))`.
Default names are used when `col_names` is not specified.
Unfortunately and I don't know why, it only works without multiprocessing, so I added back the non-multiprocessing part in `strategy()`.
Let me know what you think,
DrParikaa
=> Updated core.py - Option to rename indicators

README.md
@twopirllc,
I took the initiative to re-organize a bit the README. I also added a table of contents to improve readability.
Let me know what you think,
DrPaprikaa
=> Re-organized README and added a TOC

pandas_ta/__init__.py, pandas_ta/core.py, pandas_ta/volatility/__init__.py, pandas_ta/volatility/thermo.py, tests/test_ext_indicator_volatility.py, tests/test_indicator_volatility.py
=> Elders thermometer

pandas_ta/volatility/atr.py
The function always calculated ATR in EMA mode.
Changed code and documentation a little bit, to fix it.
=> ATR MA update in line with TradingView

pandas_ta/trend/decreasing.py, pandas_ta/trend/increasing.py
Added strictly bool parameter to check series is strictly continuous increasing or decreasing
=> Strictly continuous increasing or decreasing

pandas_ta/core.py, pandas_ta/volume/__init__.py, pandas_ta/volume/pvr.py, tests/test_indicator_volume.py
Added Price Volume Rank Indicator
=> ENH #163 Adding Price Volume indicator

README.md
Hi @twopirllc,
A simple PR to add the number of contributors as a badge at the top of the README.
Cheers,
DrPaprikaa
=> Added 'contributors' badge to README

README.md, pandas_ta/core.py, pandas_ta/momentum/__init__.py, pandas_ta/momentum/td.py, tests/test_ext_indicator_momentum.py, tests/test_indicator_momentum.py
Added TD sequential indicator.
see https://tradetrekker.wordpress.com/tdsequential/
=> td sequential

pandas_ta/trend/adx.py
There should be a additional parameter so ADX smoothing and DI Length can have different values. I compared it to TradingViews DMI calculation and they also offer this.
Thanks for this great lib!
=> Update adx to include lensig

pandas_ta/core.py, pandas_ta/momentum/__init__.py, pandas_ta/momentum/dm.py, pandas_ta/trend/psar.py
Parabolic Stop and Reverse (PSAR) construction did change as well as trend direction initialisation with Directional Movement (DM).
=> BUG #180 psar with dm init

pandas_ta/core.py
=> VWMA Param fix

pandas_ta/core.py
Fix cleanup of multiprocessing resources to prevent leaks
=> Multiprocessing cleanup

pandas_ta/__init__.py, pandas_ta/core.py, pandas_ta/momentum/__init__.py, pandas_ta/momentum/squeeze_pro.py, tests/test_ext_indicator_momentum.py, tests/test_indicator_momentum.py
Added a new indicator called squeeze_pro.
Added unit tests.
=> TTM Squeeze PRO indicator #313

README.md, pandas_ta/core.py, pandas_ta/overlap/ichimoku.py, pandas_ta/trend/dpo.py
Indicators with potential data leak should handle lookahead=False kwargs
=> Added lookahead interface to ichimoku and dpo indicators

pandas_ta/volatility/atr.py
=> Fix ATR Length param.

pandas_ta/overlap/jma.py
=> Jurik JMA indicator

pandas_ta/__init__.py
Adds the hwma indicator to the overlap strategy. Thanks for such an awesome library!
=> Added hwma to overlap strategy

pandas_ta/overlap/smma.py
P.S.: `gh pr create --base development` was needed for pr. previously not used `--base development` :)
=> fix a simple bug not to get initial ma value correctly

README.md, pandas_ta/__init__.py, pandas_ta/core.py, pandas_ta/transform/__init__.py, pandas_ta/transform/cube.py, pandas_ta/transform/ifisher.py, pandas_ta/transform/remap.py
- new category 'transform'
new Indicators:
- cube
- ifisher
- remap
=> ADD new transform category plus 3 indicators

pandas_ta/momentum/cg.py, pandas_ta/overlap/linreg.py
This pull closes https://github.com/twopirllc/pandas-ta/issues/507 and https://github.com/twopirllc/pandas-ta/issues/510. Please let me know if you need anything else.
=> Minor Bug Fix for CG and CTI

pandas_ta/overlap/rma.py
=> RMA: use SMA for seeding the series

pandas_ta/momentum/stoch.py
Emulated from MACD Histogram. Please proofread :)
=> feat(Stochastic): Add Histogram column like `STOCHh_14_3_3`

README.md, pandas_ta/momentum/td_seq.py, pandas_ta/statistics/tos_stdevall.py, pandas_ta/trend/cksp.py, pandas_ta/trend/psar.py, pandas_ta/utils/data/polygon_api.py, pandas_ta/volume/ad.py, pandas_ta/volume/adosc.py, pandas_ta/volume/eom.py, pandas_ta/volume/kvo.py, setup.py, tests/test_ext_indicator_trend.py, tests/test_indicator_statistics.py
Another round of readability. Focus on `.py` files this round
=> Readability improvements r2

pandas_ta/candles/ha.py
Feel free to use or reject, I just wanted to offer my own code to give back and help. 
I got frustrated that the HA candles took longer than anything else, so I removed the pandas operations that were slowing it down. This is 100x faster and gives the same result to within 4 decimal places.
=> ha 100x faster using numpy/numba

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/test.yml, setup.py
This is a mirror PR of #582 but against the development branch.
=> Add GHA workflow for testing to the development branch

pandas_ta/core.py, pandas_ta/overlap/__init__.py, pandas_ta/overlap/pivot.py
according to issues added Pivot indicator
=> add pivots

pandas_ta/custom.py
This PR fixes the `bind` function in `custom.py` and ensures `__pycache__` dirs and `__init__.py` files aren't processed as indicators or directories containing indicators. I tested on many indicators. It added them to specific studies desired; so that they could be called with `df.ta.study("study_name")`. It also allowed for calling the added indicators with the standard methods (`df.ta.indicator_name` and `ta.indicator_name`). Please let me know if you'd like any improvements to this PR.
=> Bugfix for custom.py

pandas_ta/momentum/stoch.py
added null check.added null check. in development branch
=> added null check. in development branch 

pandas_ta/overlap/zlma.py
getattr() wtih the mamode variable is potentially simpler
=> Proposed alternate approach to zlma ma-modes #394

pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/overlap/__init__.py, pandas_ta/overlap/chandelier_exit.py
Adding the Chandelier Exit indicator under `overlap` category. The logic for calculation is picked from #559
=> Adding Chandelier Exit Indicator

.github/ISSUE_TEMPLATE/bug_report.md
hi,
i converted support and resistance from tradingview to python
this is also associated with #217 
[https://www.tradingview.com/v/JAW0oW7R/](https://www.tradingview.com/v/JAW0oW7R/)
=======================================================
```python
import ccxt
import pandas_ta as pta
import pandas as pd
import time
exchange = ccxt.binance({
'enableRateLimit': True,
'options': {
'defaultType': 'future',  # ←-------------- quotes and 'future'
},
})
_market="BTCUSDT"
ohlc = exchange.fetch_ohlcv(_market,limit=500, timeframe='5m')
df = pd.DataFrame(ohlc, columns = ['time', 'open', 'high', 'low', 'close', 'volume'])
df['time'] = pd.to_datetime(df['time'], unit='ms')
time.sleep(1)
df[['ha_open','ha_high','ha_low','ha_close']] = pta.ha(df['open'],df['high'],df['low'],df['close']) …
```
=> support and resistance indicator supres.py

pandas_ta/candles/cdl_inside.py, pandas_ta/trend/aroon.py, pandas_ta/trend/decay.py
Hi @twopirllc 
I have created pull requests on the development branch
Hope you find it well.
Thanks
=> Issue #704 #714 Fixes

pandas_ta/utils/_stats.py, tests/test_utils.py
=> Fixed numpy import errors in development branch
