twopirllc/pandas-ta

pandas_ta/overlap/supertrend.py
Supertrend needs to be cold-started after the initial set of specified periods (default = 10).
If the initial trend is not set, the high and low value keep on fluctuating and we don't get a definite trend till there is a high-volume day that breaches the high or low value for a day. This is a rare occurrence (especially for low volatility stocks).
This might cause the trend to be set to 0 for over 100 periods in case of a range-bound ticker. 
For weekly data, it might lead to trend not being set for over a year (An issue I faced which caused me to make the change here).
The key problem was that the range fluctuates higher or lower if trend = 0. For trend = +1 and -1, the range is set to max and min respectively. This allows the line to tripped and the trend to change in case of price …
=> Solving for cold start in supertrend - setting a default trend value of +1

pandas_ta/statistics/stdev.py, pandas_ta/statistics/variance.py
When calculation variance we can divide the calculation by N, or by N-1.
When calculating sample variance we divide by N-1 (like in the current code).(https://towardsdatascience.com/why-sample-variance-is-divided-by-n-1-89821b83ef6d)
Sometimes We want to divide by N like the basis formula, to calculate population variance. (https://en.wikipedia.org/wiki/Variance#Discrete_random_variable)
For me its useful to add another parameter that will make it possible to calculate both of then using one function.
Is it useful for you?
=> Change to Variance and Std

pandas_ta/core.py
@twopirllc,
In the case where an indicator returns a `df`, I added an option in `_post_process()`, via `kwargs`, to append only specific columns to the data. It goes like this :
```
CustomStrategy = ta.Strategy(
name="MyStrat",
ta=[
{'kind':'bbands', 'params':(20,), 'col_numbers':(0,2)},
]
)
```
or alternatively : `ao = df.ta.bbands(append=True, col_numbers=(0,2))`
which can be usefull if the user needs only the upper and lower bbands for example.
Thanks,
DrPaprikaa
=> Update _post_process() in core.py

pandas_ta/core.py
`core.py::bbands` was taking in `stdev` and passing it to `volatility/bbands.py::bbands`, which expected `std`. The parameter got ignored, resulting in only ever creating `_2.0` bband columns.
Not sure which abbreviation you prefer - I saw occurrences of both across the repo. Happy to switch to the other one if you prefer.
=> fix passing incorrect stdev parameter to bbands

pandas_ta/__init__.py
Currently, the version is not set if the `try-except` block errors out.
=> Setting version regardless

pandas_ta/__init__.py, pandas_ta/core.py, pandas_ta/overlap/__init__.py, pandas_ta/overlap/mcg.py
Hi, I've added the McGinley Dynamic indicator which I have found useful but isn't yet in this package. It should work but let me know if you need anything.
=> Adding McGinley Dynamic indicator

README.md, pandas_ta/core.py, tests/test_strategy.py
Hi.
I just added the ability to turn off multiprocessing in strategies. I also updated the README and added test for it.
This is usefull when you want to run a strategy on different windows independently, so it is better to use multiprocessing on windows not on indicators and you can't have nested multiprocessing (this was my case and with multiprocessing on windows, i had 6x improvement in running time), or you have small number of indicators (Compare the running time of "Custom A" and "Custom A with No Multiprocessing" tests).
=> ENH add no multiprocessing option to strategy

pandas_ta/volatility/bbands.py
After https://github.com/twopirllc/pandas-ta/commit/fcaf5e90e1af9a05221eb8e0628a99eee256ed9c and https://github.com/twopirllc/pandas-ta/commit/18aacc8eab2ad28962c506e242e3d719c005fe2d, the method documentation regarding the default length and moving average mode parameters became misaligned
=> Updated docs reflecting the length default value

pandas_ta/volatility/true_range.py
There is an issue in high_low_range calculation of true_range() due argument drift. The introduction of NaN in close_prev (first cycles) must propagate in the calculation.
#237 true_range() function are not propagating drift parameter in the inputs - NaN values.  
I tested the solution and it is fine.
=> Fix drift argument in the true range calculation

pandas_ta/performance/trend_return.py
Please see issue #242. Originally, trade_offset=0 returned the same result as trade_offset=-1.
=> Allow trade_offset to be 0 in trend_return

README.md, pandas_ta/__init__.py, pandas_ta/candles/__init__.py, pandas_ta/candles/cdl_pattern.py, pandas_ta/core.py, tests/test_indicator_candle.py
Add a function to wrap all candle patterns from TA-Lib and pandas-ta.
**Has breaking change. (`cdl_doji` and `cdl_inside` removed)**
=> ENH add cdl_pattern

examples/AIExample.ipynb
In performance/percent_return.py:
pct_return = close.pct_change(length) # (close / close.shift(length)) - 1
So, when calculate back, it should be:
cum return = (1 + pct_return).cumprod() -1
As the close of today has been used for calculation, we cannot earn the return of today. Our trade decision only earn the return of next day.
BTW, nice example, appreciated for the good job!
=> bugfix Cum. Active Returns with cumprod

pandas_ta/volume/vp.py
Divide bins evenly by price if sort_close. Fixes #318 
Positive and negative volume based on price direction, not volume direction. Fixes #319 
Minor refactoring for clarity.
=> Fixes for Volume Profile

pandas_ta/trend/psar.py
This is consistent with other indicators that return numeric values, rather than boolean.
=> made reversal int type

pandas_ta/momentum/cmo.py, tests/test_indicator_momentum.py
So there's a TA-Lib way of calculating CMO which uses RMAs instead of rolling sums. There's even a kwarg switch to use the default method. Unfortunately the switch is ignored when TA-Lib is installed. That's what i'd propose to change. Thanks for your great effort!
=> Allow to use non TA-Lib way of calculating CMO with TA-Lib installed

examples/ni.py, pandas_ta/custom.py
Hi KJ, 
Basically this pull-request concerns what I asked about in this closed issue https://github.com/twopirllc/pandas-ta/issues/264
I added a new module custom.py with all required functionality and an example indicator that can be used as a template (the same one used in the issue ni.py). I put ni.py in the examples folder.
The usage is described in the import_dir-function of the custom module.
```
Import a directory of custom indicators into pandas_ta
Args:
dir_path (str): Full path to your indicator tree
verbose (bool): If True verbose output of results
This method allows you to experiment and develop your own technical analysis
indicators in a separate local directory of your choice but use them seamlessly 
together with the existing pandas_ta functions just like if they were part …
```
=> Proposed new way to dynamically add and test out indicators without modifying pandas_ta itself

README.md, pandas_ta/momentum/smi.py, pandas_ta/momentum/tsi.py, tests/test_indicator_momentum.py
Hi KJ,
Thanks for allowing me to contribute to this awesome project! This PR adds the signal line to the TSI as discussed in issue #351.
I have also adjusted the SMI slightly to account for the change.
I have tested and verified the changes manually as well as via your momentum testing script:
I used a default signal value of `13` which is in line with that of TradingView.
Regards,
Daniel
=> Add signal line to TSI

pandas_ta/utils/_signals.py, tests/test_utils.py
This is the most explicit implementation, which allows this edge case to be addressed directly. In this way, other developers should be able to understand the purpose for this specific detail. There may be a fancier way of handling this, but it would likely obscure the logic, so I have not pursed it.
I have also added on to the test case to ensure that first entry is always `False`. Even if another implementation is chosen, this should be specifically checked to ensure that a false signal is not generated. I have used the existing fixture by swapping the order of the series in the `cross()` invocation. This ensure that `series_a[0] <= series_b[0]` to address the edge case identified. If this condition seems out of place, it may warrant a comment, which I will add if desired.
Closes #426
=> Fix cross utility edge case

pandas_ta/momentum/apo.py, pandas_ta/momentum/cci.py, pandas_ta/momentum/dm.py, pandas_ta/momentum/macd.py, pandas_ta/momentum/ppo.py, pandas_ta/momentum/roc.py, pandas_ta/momentum/stochf.py, pandas_ta/overlap/dema.py, pandas_ta/overlap/t3.py, pandas_ta/overlap/tema.py, pandas_ta/overlap/trima.py, pandas_ta/statistics/stdev.py, pandas_ta/volatility/atr.py, pandas_ta/volatility/bbands.py, pandas_ta/volatility/natr.py, pandas_ta/volume/adosc.py, pandas_ta/volume/mfi.py
Hello Kevin,
I've noticed that the _talib_ kwarg is not propagated to inner function calls in some places. For example calling `bbands(.., talib=False)` has no effect on internal call to `stdev()` - which still uses Ta-Lib implementation of stdev.
Thanks,
Olaf
=> talib kwarg propagation

pandas_ta/overlap/supertrend.py
Parameter atr_length is required in supertrend() , because it gives a more flexibility to analyze the data as required with different length of data. Considering a use case, i.e, atr_length=100 gives more reflective analysis for stocks prices rather atr_length being equal to data parameter length.
=> Adding Parameter atr_lenght to supertrend()

pandas_ta/overlap/ema.py
During executing macd function there is  FutreWarning:
FutureWarning: The behavior of series[i:j]with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g.series[i]lookups. To retain the old behavior, useseries.iloc[i:j]. To get the future behavior, use series.loc[i:j].
This was described in #610 .
=> FutreWarning during execution of macd function

pandas_ta/utils/_validate.py
Use the union Int type rather than int.  Allows more int-like types to be used, namely numpy.int64
=> v_int: more robust casting to int

pandas_ta/overlap/ichimoku.py, pandas_ta/overlap/ssf.py, pandas_ta/statistics/kurtosis.py, pandas_ta/statistics/skew.py, pandas_ta/statistics/tos_stdevall.py, pandas_ta/trend/dpo.py
I added some warnings on dpo and ichimoku so that people can find their potential data leakage more easily.
Also `lookahead` arg was not mentioned, so I added it as well.
Discussion here: https://github.com/twopirllc/pandas-ta/issues/60#
=> Add warning docstring about data leakage on ML

pandas_ta/utils/_validate.py
Took me a while to understand why some of the passed window lengths are ignored, and it turned out that they are checked for being int but not np.integer, which is often the case when you want to test windows coming from a numpy array.
=> Extend int/float type checks with numpy scalar types

.github/ISSUE_TEMPLATE/bug_report.md, pandas_ta/__init__.py, pandas_ta/core.py, pandas_ta/trend/__init__.py, pandas_ta/trend/alphatrend.py, pandas_ta/trend/zigzag.py
Hi again @twopirllc
I removed my previous fork, but I understood that I was not right doing that, cause I added the code to main branch anyway and then send PR to development branch. Or maybe I am wrong again. If so please let me know and make any modifications you want.
Thank you
=> Zigzag indicator implemented from issue #443

pandas_ta/overlap/supertrend.py
atr_mamode will be passed on to ATR as mamode.
Useful because many libraries/platforms use SMA for calculating ATR leading to different values for supertrend.
Ref #724
=> Added atr_mamode argument to supertrend

pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/momentum/__init__.py, pandas_ta/momentum/tmo.py, tests/test_indicator_momentum.py, tests/test_studies.py
Added TMO indicator, addressing issue #700. defaults 14/5/3 values. See documentation for the calculation, defaults, and variants presented by some common platforms, also listed in the references.
Added example [jupyterlab notebook](https://github.com/luisbarrancos/pandas-ta/blob/pr_issue_700/examples/TMO_indicator.ipynb) showing how we can trivially compute the necessary information to replicate the expected results from other platforms. Added as well the respective plots with matplotlib, plotly, bokeh, with conditional shading.
=> Add True Momentum Oscillator (TMO)

README.md, pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/momentum/__init__.py, pandas_ta/momentum/crsi.py, tests/test_indicator_momentum.py, tests/test_studies.py
Implement the Connors RSI using the Wilder's RSI indicator, as discussed in #349 .
This implementation is using Pandas-TA built-in (W)RSI for the closing price and streak RSI, and using NumPy for the streaks computation and percent rank computation.
It was tested with OHLCVA timeseries with 1 million entries, and *timeit* shows that for the native RSI without TA-lib we have
```
Total execution time for crsi: 4.437666 seconds
Average execution time for crsi: 0.221883 seconds
```
while with TA-lib we have:
```
Total execution time for crsi: 3.447122 seconds
Average execution time for crsi: 0.172356 seconds
```
for an average of 20 runs.
The screenshot below shows only 251 trading days of OHLCVA data of a security, and the lookback period is 100 (the defaults are 2/3/100 for this indicator) …
=> Implement Connors RSI

pandas_ta/momentum/tmo.py
This fixes #742, adding a function to compute the sum of the signed deltas of the current day close and preceding days open, for  a given window. Doctests are included, but it should be mentioned that since the series is padded with NaNs to match the input series lengths, Pandas Series equality tests aren't suitable, due to the integer to float promotion and the need to deal with NaNs, so we have rely on ```np.allclose``` function with precision limits and NaN dealing.
Now the results match the TV indicators, but here again, some mentions are needed about the profusion of TMO indicators and implementations.
This implemention [here](https://www.tradingview.com/script/o9BQyaA4-True-Momentum-Oscillator/) is incorrectly computing the TMO since it's considering the current closing price and …
=> Add fix for #742

pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/trend/__init__.py, pandas_ta/trend/ht_trendline.py
I implemented the Hilbert Transform Instantaneous Trendline in pandas-ta by studying the mathematical principles of the Z-transform and reverse-engineering TALIB's C implementation. Through rigorous testing, I ensured that the results produced by ht_trendline match those generated by TALIB's implementation, thus enhancing the technical analysis capabilities of the pandas-ta library and closing issue #411 .
In addition, I further enhanced its performance by leveraging the Numba library, thereby significantly boosting the execution speed. This experience allowed me to deepen my understanding of Numba's capabilities and its integration within the project structure. Furthermore, I refined my Git proficiency by creating a new branch locally and generating the pull request towards the …
=> Implement Hilbert Transform Trendline, closes issue #411

pandas_ta/momentum/roc.py, pandas_ta/performance/percent_return.py
The default length for ROC as coded is 10.
```python
length = v_pos_default(length, 10)
```
However, the documentation incorrectly states the default length as 1:
```python
Args: 
close (pd.Series): Series of 'close's
length (int): It's period. Default: 1 
scalar (float): How much to magnify. Default: 100
talib (bool): If TA Lib is installed and talib is True, Returns
the TA Lib version. Default: True
offset (int): How many periods to offset the result. Default: 0
```
This PR replaces `length (int): It's period. Default: 1` with `length (int): Its period. Default: 10`
A similar issue is found with `percent_return`:
`length (int): It's period. Default: 20` is replaced with `length (int): Its period. Default: 1` since length defaults to 1, not 20, in performance/percent_return.py: `length = …
=> Fix ROC and percent_return default length documentation

pandas_ta/overlap/pivots.py
Proposed fix for Yearly pivots causes error with pandas 2.x #732
=> Bug fix for issue 732 Yearly pivots causes error with pandas 2.x

pandas_ta/momentum/td_seq.py
I'm not familiar with this particular indicator, but the slowness was caused by the use of apply function on the rolling window in `calc_td()`
Using the Pandas native functions `cumsum()` and `where()` should give the same results. The test data I used confirmed it was the same, but not sure if needs additional test cases.
Original performance as reported by cProfile
```sh
res = cProfile.run("momentum.td_seq(df['Close'])", sort='tottime')
2706808 function calls (2669110 primitive calls) in 2.399 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
30162    0.165    0.000    0.192    0.000 generic.py:6233(__finalize__)
602524/589996    0.137    0.000    0.268    0.000 {built-in method builtins.isinstance}
109722    0.107    0.000    0.133 …
```
=> td_seq perf improvement

pandas_ta/core.py, pandas_ta/volume/pvi.py, tests/test_indicator_volume.py
There are 2 PVI indicators on TradingView.
One calculates PVI using
```C
pvi := na(pvi[1]) ? initial : (change(volume) > 0 ? pvi[1] * close / close[1] : pvi[1])
```
The other uses
```C
nRes = iff(volume > volume[1], nz(nRes[1], 0) + xROC, nz(nRes[1], 0))
```
Both of them are different, and neither of them follow the logic outlined on most websites, e.g.
```
https://www.investopedia.com/terms/p/pvi.asp
https://www.kotaksecurities.com/share-market/what-is-positive-volume-index/
https://www.barchart.com/education/technical-indicators/positive_volume_index
https://www.angelone.in/knowledge-center/share-market/pvi
```
Which all show the formula as
```C
Yesterday’s PVI + [[(Close – Yesterday’s Close) / Yesterday’s Close] * Yesterday’s PVI
```
There are other definitions of the formula available …
=> PVI update to match Investopedia definition and fix for issue 625

pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/trend/__init__.py, pandas_ta/trend/zigzag.py
Hello @twopirllc 
I'm pleased to present a new pull request for the completion of the zigzag indicator.
In this update, I've utilized Numba for implementation, as opposed to the previous approach which relied on Pandas. and compared the results with TradingView's default zigzag indicator and everything seems to be so much similar.
Below, you'll find the outcome of applying a deviation of 5% and a pivot leg of 10 to the BTCUSD daily chart:
Compare this with the result of the new implementation under the same configuration:
In order to test it yourself, use the following code:
```python3
import sys
import importlib
import numpy as np
from numba import njit
import yfinance as yf
import plotly.graph_objects as go
sys.path.insert(1, '/path-to/pandas-ta')
from pandas_ta import zigzag
ticker = …
```
=> Zigzag indicator implementation using numba will close issue #443 and complete pr #693

pandas_ta/core.py, pandas_ta/maps.py, pandas_ta/trend/__init__.py, pandas_ta/trend/zigzag.py
Hello @twopirllc and @KilianB
I am making this pr to solve the issue @KilianB reported in #761 some hours ago.
The problem happens when there's two extremums in a single candle, e.g. we can see local max and min in `2021-09-07 00:00:00` candle.
To handle this, I simply continued the code when this situation happens and as a result, one of the two consecutive swings disappear:
@twopirllc kindly find the better solution and if you needed any guidance with the code I wrote, do not hesitate to let me know. I also made another local branch in my fork and then made this pr, so you can consider whether or not close the previous pr #761 
To explain more about code components, there are three functions: First I defined a rolling window function `np_rolling_hl` to find local min/max according to …
=> New zigzag

pandas_ta/momentum/stc.py, pandas_ta/trend/psar.py
Two updates in this PR to address the next slowest indicators. Also a proposed logic change to PSAR see below
STC - All I was able to do was to combine the 2 for loops into 1. Performance is around twice as fast as previous version
**Orig STC**
```
132884 function calls (132735 primitive calls) in 0.113 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
8441    0.031    0.000    0.067    0.000 series.py:1086(__getitem__)
8441    0.017    0.000    0.029    0.000 series.py:1211(_get_value)
1    0.013    0.013    0.089    0.089 stc.py:300(schaff_tc)
8481    0.008    0.000    0.009    0.000 series.py:827(_values)
1    0.005    0.005    0.005    0.005 {built-in method _imp.create_dynamic}
2516    0.005    0.000    0.005    0.000 {built-in …
```
=> STC and PSAR performance improvements
